name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨 3 点运行 (UTC 时间，约北京时间上午 11 点)
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          # 使用 Personal Access Token (PAT) 而不是默认的 GITHUB_TOKEN
          # 以确保有权限推送更新到 fork 仓库
          token: ${{ secrets.SYNC_PAT }}
          # 获取所有历史记录，以便正确进行 merge
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Actions Sync"
          git config user.email "actions-sync@github.com"

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: |
          # 假设需要同步的是 master 分支
          # 如果你的 fork 或上游仓库使用 main，请修改为 main
          git checkout master
          git merge upstream/master --no-edit # 使用 --no-edit 避免交互式提交信息编辑
        # 注意：如果你的 fork 的 master 分支有与上游不同的提交，这里可能会产生合并冲突！
        # 这个简单的脚本不会自动解决冲突。

      - name: Push Changes to Fork
        run: git push origin master
        # 如果上一步发生冲突导致 merge 失败，这一步也会失败
